site_name: Prefecto
site_url: https://dominictarro.github.io/prefecto/
repo_url: https://github.com/dominictarro/prefecto
theme: readthedocs

nav:
  - "Home": index.md
  - "License": license.md
  - "Reference":
    - "Blocks": blocks.md
    - "Concurrency":
      - "Batch Task": concurrency/batch_task.md
      - "Kill Switches": concurrency/kill_switch.md
    - "Logging": logging.md

plugins:
  - search:
  - mkdocstrings:
      default_handler: python
      enable_inventory: true
      handlers:
        python:
          options:
            show_source: false
