site_name: Prefecto
site_url: https://prefecto.readthedocs.io
repo_url: https://github.com/dominictarro/prefecto
theme: readthedocs

nav:
  - Home: index.md
  - "Concurrency":
    - batch_task.md
  - "Serialization":
    - serializers/extended_serializer.md
    - serializers/method.md
    - serializers/functions.md
    - "Pandas":
      - serializers/pandas/methods.md


plugins: 
  - search:
  - mkdocstrings:
      default_handler: python
      enable_inventory: true
      handlers:
        python:
          options:
            show_source: false
