site_name: Prefecto
site_url: https://dominictarro.github.io/prefecto/
repo_url: https://github.com/dominictarro/prefecto
theme: readthedocs

nav:
  - "Home": index.md
  - "License": license.md
  - "Reference":
    - "Concurrency": concurrency.md

plugins:
  - search:
  - mkdocstrings:
      default_handler: python
      enable_inventory: true
      handlers:
        python:
          options:
            show_source: false
